#!/bin/bash
# Scheduled audit: run leartech convention rules against main branches.
# Posts GitHub Issues for findings — creates cleanup backlog.
#
# Usage: /app/cron-audit.sh --repos "repo1,repo2" --org mikelear \
#          --cluster-id gcp --token ghp_xxx
set -euo pipefail

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repos) REPOS="$2"; shift 2 ;;
    --org) ORG="$2"; shift 2 ;;
    --cluster-id) CLUSTER_ID="$2"; shift 2 ;;
    --token) GIT_TOKEN="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

ORG="${ORG:-mikelear}"
CLUSTER_ID="${CLUSTER_ID:-unknown}"
DRY_RUN="${DRY_RUN:-false}"
# Rules path: /app/rules/leartech in Docker, override with LEARTECH_RULES env for local testing
LEARTECH_RULES="${LEARTECH_RULES:-/app/rules/leartech}"
WORK_DIR="/tmp/audit"
AUDIT_LABEL="audit-convention"
TOTAL_FINDINGS=0
TOTAL_ISSUES=0

echo "=== Leartech Convention Audit [${CLUSTER_ID}] ==="
echo "Repos: $(echo "$REPOS" | tr ',' '\n' | wc -l | tr -d ' ')"
echo "Dry run: $DRY_RUN"
echo ""

mkdir -p "$WORK_DIR"

IFS=',' read -ra REPO_LIST <<< "$REPOS"

for REPO in "${REPO_LIST[@]}"; do
  REPO=$(echo "$REPO" | xargs)  # trim whitespace
  REPO_DIR="$WORK_DIR/$REPO"
  echo "============================================================"
  echo "Scanning: $ORG/$REPO (main)"
  echo "============================================================"

  # Clone
  git clone --depth 1 "https://x-access-token:${GIT_TOKEN}@github.com/${ORG}/${REPO}.git" "$REPO_DIR" 2>/dev/null || {
    echo "  SKIP: failed to clone $ORG/$REPO"
    continue
  }

  # Run leartech semgrep rules
  RESULTS_FILE="$WORK_DIR/${REPO}-results.json"
  semgrep scan --config "$LEARTECH_RULES" \
    --json \
    --output "$RESULTS_FILE" \
    "$REPO_DIR" 2>/dev/null || true

  FINDING_COUNT=$(jq '.results | length' "$RESULTS_FILE" 2>/dev/null || echo "0")
  echo "  Findings: $FINDING_COUNT"

  if [ "$FINDING_COUNT" -eq 0 ]; then
    echo "  CLEAN"
    rm -rf "$REPO_DIR"
    continue
  fi

  TOTAL_FINDINGS=$((TOTAL_FINDINGS + FINDING_COUNT))

  # Build issue body
  ERRORS=$(jq '[.results[] | select(.extra.severity == "ERROR")] | length' "$RESULTS_FILE" 2>/dev/null || echo "0")
  WARNINGS=$(jq '[.results[] | select(.extra.severity == "WARNING")] | length' "$RESULTS_FILE" 2>/dev/null || echo "0")
  INFOS=$(jq '[.results[] | select(.extra.severity == "INFO")] | length' "$RESULTS_FILE" 2>/dev/null || echo "0")

  FINDINGS_TABLE=$(jq -r '.results[] | "| \(.extra.severity) | \(.check_id | split(".")[-1]) | `\(.path | split("/") | .[-2:] | join("/")):\(.start.line)` | \(.extra.message | gsub("\n"; " ") | .[:100]) |"' "$RESULTS_FILE" 2>/dev/null)

  ISSUE_TITLE="[audit] ${FINDING_COUNT} leartech convention violation(s) on main"
  ISSUE_BODY="## Leartech Convention Audit

Scheduled scan of \`main\` branch found **${FINDING_COUNT}** convention violation(s).

| Severity | Count |
|---|---|
| ERROR | ${ERRORS} |
| WARNING | ${WARNINGS} |
| INFO | ${INFOS} |

### Findings

| Severity | Rule | Location | Message |
|---|---|---|---|
${FINDINGS_TABLE}

---

**How to fix:** Each rule references a section in [hub/shared-rules/conventions.md](https://github.com/${ORG}/leartech-hub/blob/main/shared-rules/conventions.md).

**Not blocking** — these are existing violations on main, not from a specific PR. Add to your cleanup backlog.

*Generated by leartech convention audit CronJob [\`${CLUSTER_ID}\`]*"

  # Check if an open audit issue already exists (avoid duplicates)
  EXISTING=$(curl -s -H "Authorization: token $GIT_TOKEN" \
    "https://api.github.com/repos/${ORG}/${REPO}/issues?labels=${AUDIT_LABEL}&state=open&per_page=1" \
    | jq 'length' 2>/dev/null || echo "0")

  if [ "$EXISTING" -gt 0 ]; then
    echo "  Open audit issue already exists — updating"
    ISSUE_NUMBER=$(curl -s -H "Authorization: token $GIT_TOKEN" \
      "https://api.github.com/repos/${ORG}/${REPO}/issues?labels=${AUDIT_LABEL}&state=open&per_page=1" \
      | jq '.[0].number')

    if [ "$DRY_RUN" = "false" ]; then
      curl -s -o /dev/null -X PATCH \
        -H "Authorization: token $GIT_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/${ORG}/${REPO}/issues/${ISSUE_NUMBER}" \
        -d "$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" '{title: $title, body: $body}')"
      echo "  Updated issue #${ISSUE_NUMBER}"
    else
      echo "  DRY RUN: would update issue #${ISSUE_NUMBER}"
    fi
  else
    echo "  Creating new audit issue"
    if [ "$DRY_RUN" = "false" ]; then
      RESPONSE=$(curl -s -X POST \
        -H "Authorization: token $GIT_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/${ORG}/${REPO}/issues" \
        -d "$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" --arg label "$AUDIT_LABEL" \
          '{title: $title, body: $body, labels: [$label]}')")
      NEW_NUMBER=$(echo "$RESPONSE" | jq '.number')
      echo "  Created issue #${NEW_NUMBER}"
    else
      echo "  DRY RUN: would create issue"
      echo "  Title: $ISSUE_TITLE"
    fi
  fi

  TOTAL_ISSUES=$((TOTAL_ISSUES + 1))
  rm -rf "$REPO_DIR"
done

echo ""
echo "============================================================"
echo "Audit complete"
echo "  Repos scanned: ${#REPO_LIST[@]}"
echo "  Total findings: $TOTAL_FINDINGS"
echo "  Issues created/updated: $TOTAL_ISSUES"
echo "============================================================"
